version: "3.9"
services:
  app:
    build: .
    env_file: .env
    ports:
      - "8200:8200"
    volumes:
      - ./public/images:/app/public/images
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8200/health"]
      interval: 10s
      timeout: 3s
      retries: 5


  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
