services:
  app:
    build: .
    env_file: .env
    ports:
      - "8200:8200"
    volumes:
      - ./public/images:/app/public/images
      - ./database:/app/database
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8200/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks: [monitor]

  prometheus:
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on: [app]
    networks: [monitor]

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on: [prometheus]
    networks: [monitor]

networks:
  monitor: {}