name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint || echo "lint warnings only"

      - name: Tests
        run: npm test

      - name: Build Docker image
        run: docker build -t bookapp:ci .

      - name: Run container & healthcheck
        run: |
          docker run -d -p 8200:8200 --name bookapp-ci bookapp:ci
          for i in {1..30}; do
            if curl -fsS http://localhost:8200/health >/dev/null; then
              echo "App is healthy"; break
            fi
            echo "Waiting for health..." && sleep 2
          done
          docker logs bookapp-ci || true

      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/bookapp:latest"
          docker tag bookapp:ci $IMAGE
          docker push $IMAGE

      - name: Cleanup container
        if: always()
        run: docker rm -f bookapp-ci || true
